# Site settings
title: Oliver Burn
email: oliver AT puppycrawl DOT com
description: > # this means to ignore newlines until "baseurl:"
  Oliver Burn's personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.puppycrawl.com" # the base hostname & protocol for your site
twitter_username: oliverburn
github_username:  oburn

timezone: Australia/Sydney

# Build settings
markdown: kramdown
